### ISSUE TITLE
Request VM(s) from Operations

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hungry-hungry-hippo#1]
- Review H2 servers (specifically for ActionCable specific differences from or normal default)
- We won't need redis (at this time)
- HTTP2 (which rails servers or proxies will need to be in place?)
- What mounts need to be included?
- If we don't use SDR-API we need to dor-workspace and globus endpoint(s) mounted.

**Done when**: we have servers available that support Rails 8 deployments with HTTP2 support.

**Comment by lwrubel** [comment]
Submitted here: https://github.com/sul-dlss/operations-tasks/issues/3904

**Comment by aaron-collier** [comment]
@lwrubel I think we can close this now, can you confirm?
