### ISSUE TITLE
Implement application deployment

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hungry-hungry-hippo#10]
Add the necessary capistrano gems and configure capistrano for application deployment to our servers.

**Done when**:
- Capistrano is configured following our normal process.
- sdr-deploy?

**Comment by lwrubel** [comment]
Now that we https://github.com/sul-dlss/operations-tasks/issues/3904#issuecomment-2458310383 we can start setting up capistrano for deployment.

Will require https://github.com/sul-dlss/puppet/pull/11449 having been merged
