### ISSUE TITLE
Add the Authors tab and fields to the deposit work form

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hungry-hungry-hippo#113]
[See figma designs](https://www.figma.com/design/g46Nfl5EHG7DfwqupK3G4X/H2-2024?node-id=1116-3660&node-type=frame&t=TGAzCJ41ZabLtUxL-0)

Need individual and organization for MVP1.

**Comment by lwrubel** [comment]
In this MVP1 work, planning to leave out:
* Affiliations
* Re-ordering authors

Anything else that could wait until later or another ticket?
