### ISSUE TITLE
Add the license tab to the work deposit form

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hungry-hungry-hippo#116]
Initially we we default to always use CC-BY, the tab should be a simple indication of that 

[See figma design](https://www.figma.com/design/g46Nfl5EHG7DfwqupK3G4X/H2-2024?node-id=1116-5067&node-type=frame&t=TGAzCJ41ZabLtUxL-0)

**Comment by lwrubel** [comment]
Closed with #185
