### ISSUE TITLE
Style of selected invalid tab

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/hungry-hungry-hippo#186]
When there is a tab with an `is-invalid` class, it's hard to read when selected. 

![Image](https://github.com/user-attachments/assets/2ac9c029-1ada-4cc2-bdcb-3bb8420436fb)

**Comment by astridu** [comment]
Good catch! Here are a couple options. @amyehodge Let me know which you prefer.

<img width="994" alt="image" src="https://github.com/user-attachments/assets/5a2bb482-d279-4664-926e-ee6bd2a70093">

**Comment by astridu** [comment]
Also, the background gray looks a little dark. It should be 10% black.

**Comment by amyehodge** [comment]
@astridu I prefer Proposal 1. I like that the dark outline is reminiscent of the no errors color of the box.

**Comment by justinlittman** [comment]
Per @amyehodge and @astridu proposal 1 is the decision, so this is now actionable.
