### ISSUE TITLE
Generate fresh Rails 8 application

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hungry-hungry-hippo#2]
- Run `rails new...` with any specific flags we determine are appropriate for Rails 8.
- Add our core set of default gems (including dev and test specific gems)

**Done when:** we have a blank/fresh rails welcome page that can be run locally with sufficient dependencies to start development.

Extra:
 
- Review and update any DevPlayBook related documentation for Rails
- Review the docker file setup

**Comment by lwrubel** [comment]
Generated with:
```
rails new /Users/lwrubel/sul-dlss/hungry-hungry-hippo --skip-action-mailbox --skip-action-text --skip-test --skip-system-test --skip-thruster --skip-rubocop --skip-brakeman --skip-ci --skip-kamal --no-devcontainer --css=bootstrap
```
