### ISSUE TITLE
Related works drop-down should have 14 options and "this related work" text needs to be included.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/hungry-hungry-hippo#237]
I'm only seeing these, which is about half of them:
![Image](https://github.com/user-attachments/assets/9b5bb4f1-275d-4c19-956c-a0bd1473dda6)

For the "this related work" text, in the original mockup we placed this over to the right of the selection box and left it out off the end of the actual selections, but we've decided that it should be included in each of the entries instead. 

This is the mockup:

![Image](https://github.com/user-attachments/assets/d782c2ad-fc01-48ec-a5ab-a364fa6b9a55)

This is the full list of choices. I've written them with the "this related work" text appended to each entry:
It's a supplement to this related work.
It's supplemented by this related work.
It's referenced or cited by this related work.
It references or cites this related work.
It's derived from this related work.
It's the source of this related work.
The version of record / publisher's version of my deposit is this related work.
It's identical to this related work.
It has specific versions or instances, one of which is this related work.
It's a specific version or instance of this related work.
It succeeds or is a continuation of this related work.
It precedes or is continued by this related work.
It's one part of this related work.
It consists of parts, one of which is this related work.

**Comment by amyehodge** [comment]
@astridu How do you feel about putting the "this related work" text on the end of each entry instead of over to the side of the selection list? In the actual implementation, I'm feeling like having it on each entry may be easier to read.

**Comment by astridu** [comment]
I agree.
