### ISSUE TITLE
Related content tab needs white space at the bottom of the page

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/hungry-hungry-hippo#238]
The "save as draft" and "next" buttons are shoved up against the bottom edge of the window.
![Image](https://github.com/user-attachments/assets/9a500002-91d4-4734-8699-a8214aefec6f)

**Comment by justinlittman** [comment]
Can we ignore this until there is a footer?

**Comment by amyehodge** [comment]
@justinlittman I found it weirdly jarring, so, depends on when the footer will be there. Is it planned for MVP1?

**Comment by justinlittman** [comment]
@amyehodge Totally your call. If you want it in MVP1, please ticket, tag with MVP1, and drop in Ready.
