### ISSUE TITLE
Implement authorization in the works controller

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hungry-hungry-hippo#24]
Once we have basic authentication in place and a works controller with a couple actions, we should set up authorization. Consider using https://github.com/varvet/pundit

~~Blocked by #49~~

**Comment by lwrubel** [comment]
Is this a question of pundit vs ActionPolicy? Are there ActionPolicy pain points we're trying to solve with another gem?

**Comment by mjgiarlo** [comment]
@lwrubel The question I'm pondering is "is pundit sufficient for our purposes?" since pundit appears to be more widely used than AP.

**Comment by justinlittman** [comment]
AP is often hard to understand. A more intuitive library would be a win.
