### ISSUE TITLE
Dashboard table rows should not have shading

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/hungry-hungry-hippo#264]
Currently the header row and the content rows are shades of gray and the design shows them all as having the background color. 

See design:

<img width="1192" alt="Screenshot 2024-12-06 at 9 45 11 AM" src="https://github.com/user-attachments/assets/f07f6a41-b4cb-475b-a9e4-377e8f8eb7d7">

**Comment by justinlittman** [comment]
@amyehodge Is this fixed?

**Comment by amyehodge** [comment]
I still see this
<img width="1336" alt="Screenshot 2024-12-09 at 4 39 27 PM" src="https://github.com/user-attachments/assets/6e697ee3-6ace-4a1d-adcf-f38afa2f116b">

**Comment by justinlittman** [comment]
@amyehodge That's a collection show page, not a dashboard page.

**Comment by amyehodge** [comment]
@justinlittman Oh, sorry. You're right. This is indeed fixed on the dashboard.

**Comment by aaron-collier** [comment]
Fixed.

![Image](https://github.com/user-attachments/assets/3a3a3d3d-9964-482a-a20e-9bec242926fe)
