### ISSUE TITLE
Title of deposit page - viz design refinements

### ISSUE THREAD

**Issue by astridu** [sul-dlss/hungry-hungry-hippo#280]
1. Font style of text field label should be Paragraph. Spacing should be a little tighter between the label and text field. See screenshots below.
2. Missing info icon next to field label
3. Width of Title text field should be 550px
4. Border color is 40% black.

On stage:
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/f092e5cf-60f4-4c90-bdd1-6726c46025d8">

Mockup:
<img width="567" alt="image" src="https://github.com/user-attachments/assets/7a15a65c-e77f-45de-b1d4-a74d787bfaa2">

**Comment by astridu** [comment]
Not sure if these are defined in a central location somewhere for devs, but these our the font styles DLUX is using in all our apps.

https://www.figma.com/design/FE5WZAvHf2e97GJeOP3mH6/Stanford-Styles?node-id=243-50&t=aBxT00LMMDUGngLm-1

**Comment by astridu** [comment]
Looks like they were set up incorrectly in github. Darcy created a ticket for this. https://github.com/sul-dlss/component-library/issues/44

**Comment by justinlittman** [comment]
@astridu, 
"Border color is 40% black." <-- Is this standard across all of our apps? If so, it should be specified in the component library. Also, the component library doesn't have a 40% black.

**Comment by astridu** [comment]
Let me post a note in the design library slack to see where this is defined. It's in our figma component library, but maybe not yet in github.
