### ISSUE TITLE
Dates page - viz design refinements

### ISSUE THREAD

**Issue by astridu** [sul-dlss/hungry-hungry-hippo#283]
1. Border color is 40% black
2. Trash icon should be closer to date field and should be 16px (looks like it is 20px)
3. Watermarks in the date fields need to be field labels (sorry, my bad) in order to be accessible
4. Missing info icon

On stage:
<img width="672" alt="image" src="https://github.com/user-attachments/assets/10ad4513-4eb7-4eea-b3b0-e7badad0efbb">

Mockup:
<img width="359" alt="image" src="https://github.com/user-attachments/assets/9cae9e90-7258-46ad-a03f-37acd452e70b">

**Comment by justinlittman** [comment]
@astridu There are hidden labels. Are they acceptable for accessibility purposes?

**Comment by astridu** [comment]
No, they also have to be visible and can't disappear once the user starts typing or selecting a value in the field.
