### ISSUE TITLE
Determine minimal metadata fields for work form

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/hungry-hungry-hippo#32]
@amyehodge to provide requirements for MVP phase 1 minimal metadata needed for deposit form.

**Comment by aaron-collier** [comment]
See notes for MVP1 Requirements: https://docs.google.com/document/d/1q-9_OXj89agARhx80oSFNahAqru_nOE4RbmpwlWb3O4/edit?tab=t.0#heading=h.l7y53xjj0iyh
