### ISSUE TITLE
Implement breadcrumbs as described in the designs

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hungry-hungry-hippo#330]
Review how the breadcrumbs are displayed through the figma designs https://www.figma.com/design/g46Nfl5EHG7DfwqupK3G4X/H3-2024?node-id=1092-2227&node-type=canvas&t=ycXCLrdQjVVOrGwq-0 in order to implement in H3

**Comment by lwrubel** [comment]
@astridu looking at the mockups, the breadcrumbs for editing a work are:
* Dashboard > Collection Name > Untitled Deposit > Edit  (when it's an unsaved first draft)
* Dashboard > Collection Name > Work Title  (when the work has been saved as draft or preciously deposited)

The mockups seem to show "Untitled Deposit" changing to the actual title once they have entered something in the title field. Am I understanding that correctly?

Also, I'm not sure if it matters but in H2, the "Edit" breadcrumb displays on works when you go into edit them. Do we want that to happen here as well? In H2 when you are working on an "Untitled Deposit" there is no "Edit".

**Comment by lwrubel** [comment]
What size should the breadcrumb text be? In the mockups, it's part of a component, so I can't click on the text itself, but it's also possible I missed something.

**Comment by astridu** [comment]
Yes, Untitled deposit changes to the actual title once they have entered something in that field.

**Comment by astridu** [comment]
Yes, let's keep the breadcrumb behavior the same as it is today. I can add that to my mockups.

**Comment by astridu** [comment]
Breadcrumb text should be paragraph size (16pt). Thank you!
