### ISSUE TITLE
Notify user if empty folder(s) within hierarchy are being dropped during the upload.

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/hungry-hungry-hippo#389]
When uploading a hierarchy that has an empty folder buried down in the hierarchy, the empty folder does not appear in the uploaded files list (which is fine), and the user is not alerted that this has been dropped. It would be nice, but not crucial, to alert the user to this fact.

**Comment by justinlittman** [comment]
I've looked into this and it would require writing our own dropzone component.
