### ISSUE TITLE
Setup and configure Honeybadger

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/hungry-hungry-hippo#4]

**Comment by justinlittman** [comment]
The HB key has been added to vault under `hungry-hungry-hippo/honeybadger-api-key`.

Once the servers have been provisioned, the following env variables will need to be added:
* HB_API_KEY
* HB_ENV

**Comment by justinlittman** [comment]
For QA and stage: https://github.com/sul-dlss/puppet/pull/11460
